### ISSUE TITLE
Can you tell me if the UNet and VAE blocks in stable diffusion used in the model use the official pre-trained weights provided by stable diffusion or your own trained weights?

### ISSUE THREAD

**Issue by zuiaichirouya** [YuzheZhang-1999/DiffTSR#1]
I'm sorry to bother you. Can you tell me if the UNet and VAE blocks in stable diffusion used in the model use the official pre-trained weights provided by stable diffusion or your own trained weights?

**Comment by YuzheZhang-1999** [comment]
All modules are trained from scratch without any pre-training weights.

**Comment by zuiaichirouya** [comment]
Can I ask again how much computational resources would be required to train this model?

**Comment by YuzheZhang-1999** [comment]
Each module is trained on a machine equipped with 8 NVIDIA A100-40GB GPUs.

**Comment by zuiaichirouya** [comment]
Thank you very much for your answer.
