### ISSUE TITLE
关于中文文本整图超分的问题

### ISSUE THREAD

**Issue by renjd** [YuzheZhang-1999/DiffTSR#10]
作者您好，感谢您和团队开展的辛苦工作研究。我有两个问题想请教一下：
1、目前是否还没有可用于实现中文整图文本超分的模型或技术？在该仓库的其他issue下看到了相关的问题，作者给出的方法是先使用ocr技术识别到单行文本再进行超分，想问一问还有相关现成的模型或技术吗？
2、我跑通了作者提供的推理代码，这样子遍历测试图片的逻辑导致每次都要加载模型，速度非常慢，有什么其他解决办法吗？感谢回复！
![image](https://github.com/user-attachments/assets/ad698037-e68d-4667-9931-157f60a30314)

**Comment by YuzheZhang-1999** [comment]
感谢您的关注和兴趣。关于您这两个问题，回答如下
1、整图文本超分的方法可以尝试一下[DocDiff](https://arxiv.org/abs/2305.03892)，不过该模型是专注于“文档图像“的增强。本项目目前仅支持单行文本图像的超分，如果要对全图做，需要先识别文本行、然后依次超分。此外，也可以持续关注，我们也在努力实现更高效的整图文本超分。
2、因为该技术基于diffusion，因此对每一张图片的处理需要经历N步逆向扩散操作（N=200），并非每次都重新加载模型，模型在最初已经加载完成。若想提高计算效率，可以通过减小扩散步长或者模型压缩等常用的用于加速diffusion推理的技术。此外，本工作后续也可能会开源一个更轻量、效率更高的版本。
再次感谢您的关注~

**Comment by renjd** [comment]
感谢作者的耐心解答，祝研究顺利！

**Comment by renjd** [comment]
> 感谢您的关注和兴趣。关于您这两个问题，回答如下 1、整图文本超分的方法可以尝试一下[DocDiff](https://arxiv.org/abs/2305.03892)，不过该模型是专注于“文档图像“的增强。本项目目前仅支持单行文本图像的超分，如果要对全图做，需要先识别文本行、然后依次超分。此外，也可以持续关注，我们也在努力实现更高效的整图文本超分。 2、因为该技术基于diffusion，因此对每一张图片的处理需要经历N步逆向扩散操作（N=200），并非每次都重新加载模型，模型在最初已经加载完成。若想提高计算效率，可以通过减小扩散步长或者模型压缩等常用的用于加速diffusion推理的技术。此外，本工作后续也可能会开源一个更轻量、效率更高的版本。 再次感谢您的关注~

您好，前段时间我在实习，这段时间准备相关研究。请问近期有开源训练代码的打算吗？感谢回复！
