### ISSUE TITLE
Repo is too large

### ISSUE THREAD

**Issue by uhSuiL** [YuzheZhang-1999/DiffTSR#4]
- How about pushing the repo to gitee for Chinese users to clone?（国内clone太难了，经常断联超时，能不能放一份到gitee？）
- How about using some public image-hosts to display repo imgs?（把展示的图片传到图床上然后链接过来，应该能让仓库小点？）

Thanks, appreciate your work.

**Comment by YuzheZhang-1999** [comment]
Thanks for your advice.

**Comment by uhSuiL** [comment]
Thanks for your reply and appreciate your work
